---
version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_HOST: postgres
    restart: always
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - 8888:80
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: P@ssw0rd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_HOST: postgres
    restart: always
    depends_on:
      - postgres
...

