---
- hosts: centos
  become: yes
  tasks:
    - name: install apache
      dnf:
        name: httpd
        state: latest
    - name: start apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
...
